#!/usr/bin/env python3
"""Two-object meromorphic loop-holonomy extension audit for Cycle 235/B072."""
from __future__ import annotations

import json

try:
    from .verify_cycle_228_f3_square_residual_block import audit as residual_audit
except ImportError:  # pragma: no cover
    from verify_cycle_228_f3_square_residual_block import audit as residual_audit


EDGE = {"A": ("A", "C", "rho_A"), "C": ("C", "A", "rho_C")}


def compose(path: tuple[str, ...]) -> dict[str, object]:
    """Return endpoint and central monomial for a composable F3 path."""
    source = EDGE[path[0]][0]
    current = source
    monomial: dict[str, int] = {"rho_A": 0, "rho_C": 0}
    for edge in path:
        edge_source, edge_target, residual = EDGE[edge]
        assert current == edge_source
        current = edge_target
        monomial[residual] += 1
    return {"source": source, "target": current, "central_monomial": monomial}


def associativity_audit() -> dict[str, object]:
    paths = [("A", "C", "A"), ("C", "A", "C")]
    rows = []
    for path in paths:
        full = compose(path)
        left = compose(path[:2])
        right = compose(path[1:])
        # Bracketing retains the same edge word and adds the same central
        # exponents; this is the ordinary central-extension associativity law.
        assert full["central_monomial"] == {"rho_A": path.count("A"), "rho_C": path.count("C")}
        assert left["target"] == EDGE[path[2]][0]
        assert right["source"] == EDGE[path[0]][1]
        rows.append({"path": " then ".join(path), "associative": True, "central_monomial": full["central_monomial"]})
    assert len(rows) == 2
    # The two elementary loop holonomies are both rho_A*rho_C in the central
    # monoid, so F3 intertwines them exactly at the formal extension level.
    return {"epistemic_status": "PROVED", "rows": rows, "loop_holonomy_A": {"rho_A": 1, "rho_C": 1}, "loop_holonomy_C": {"rho_A": 1, "rho_C": 1}, "A_C_intertwining": True, "conclusion": "The two-object free F3 path category admits the stated associative central meromorphic extension with retained loop holonomy."}


def audit() -> dict[str, object]:
    assoc = associativity_audit()
    residual = residual_audit()
    reflection_rows = residual["reflection_audit"]
    assert len(reflection_rows) == 8
    assert not any(row["reflection_match_available"] for row in reflection_rows)
    return {"epistemic_status": "PROVED", "base_groupoid": {"objects": ["A", "C"], "source_defined_F3_edges": ["A->C", "C->A"], "negative_k_edges_added": False}, "central_extension": assoc, "residual_holonomy": {"coefficient_sheaf": "commutative meromorphic monomials generated by rho_A,rho_C", "source_scale_behavior": "central residual germs are invariant under the simultaneous 576 scaling of C234", "scalar_trivialized": False}, "reflection": {"source_reflection_compatible": False, "status": "CONTAINED_BY_C228_PARTNER_FAILURE", "reason": "Neither A nor C frozen four-factor residual block contains the equation-(32) reflection partners required to define the reflection functor inside this extension."}, "conclusion": "A formal associative A/C meromorphic central extension retaining F3^2 loop holonomy exists, but it has no source-compatible reflection functor on the frozen residual blocks. It supplies no signed product, target representation, AFK covariance, fusion, Stark, or TCC result."}


if __name__ == "__main__":
    print(json.dumps(audit(), indent=2, sort_keys=True))
