#!/usr/bin/env python3
"""Corrected exact finite-relation audit for the normalized AFK d=6 packet."""
from __future__ import annotations

import argparse
from fractions import Fraction
import json
from pathlib import Path
import subprocess
import sys


ROOT = Path(__file__).resolve().parents[1]
TRANSFER = ROOT / "discovery/cycle-185-multiplier-weighted-relation-transfer-prototype-v1.json"
MULTIPLIER = ROOT / "scripts/dimension_six_stabilizer_ledger.py"
DIMENSION = 6
Point = tuple[int, int]


def standard(point: Point) -> Point:
    return point[0] % DIMENSION, point[1] % DIMENSION


def pairing(left: Point, right: Point) -> int:
    return left[1] * right[0] - left[0] * right[1]


def standard_negative(point: Point) -> tuple[Point, int]:
    reduced = standard((-point[0], -point[1]))
    lift = ((reduced[0] + point[0]) // DIMENSION, (reduced[1] + point[1]) // DIMENSION)
    sign = -1 if pairing(lift, point) % 2 else 1
    return reduced, sign


def inversion_orbits() -> tuple[list[Point], list[tuple[Point, Point]]]:
    self_inverse = []
    pairs = []
    for point in ((a, b) for a in range(DIMENSION) for b in range(DIMENSION) if (a, b) != (0, 0)):
        inverse, _ = standard_negative(point)
        if point == inverse:
            self_inverse.append(point)
        elif point < inverse:
            pairs.append((point, inverse))
    return self_inverse, pairs


def formal_assignment(*, distinguished: Fraction) -> dict[Point, Fraction]:
    values: dict[Point, Fraction] = {(0, 0): Fraction(1)}
    seen: set[Point] = {(0, 0)}
    for point in ((a, b) for a in range(DIMENSION) for b in range(DIMENSION) if (a, b) != (0, 0)):
        if point in seen:
            continue
        inverse, sign = standard_negative(point)
        value = distinguished if point == (0, 1) else Fraction(1)
        if inverse == point:
            if sign != 1:
                raise AssertionError(("non-rational self-inverse sign", point, sign))
            values[point] = Fraction(1)
        else:
            values[point] = value
            values[inverse] = Fraction(sign, 1) / value
        seen.add(point)
        seen.add(inverse)
    return values


def check_assignment(values: dict[Point, Fraction]) -> None:
    if set(values) != {(a, b) for a in range(DIMENSION) for b in range(DIMENSION)}:
        raise AssertionError("assignment support")
    for point, value in values.items():
        if point == (0, 0):
            continue
        inverse, sign = standard_negative(point)
        if not value or value * values[inverse] != sign:
            raise AssertionError(("signed reciprocal relation", point, inverse, value, values[inverse], sign))


def payload() -> dict[str, object]:
    multiplier = json.loads(subprocess.run([sys.executable, str(MULTIPLIER)], check=True, capture_output=True, text=True, timeout=10).stdout)
    transfer = json.loads(TRANSFER.read_text())
    if not (multiplier["all_36_characteristics_fixed"] and multiplier["all_multiplier_comparisons_match"]):
        raise AssertionError("multiplier ledger drift")
    if transfer["summary"]["relation_label_count"] != 11 or not transfer["summary"]["all_triple_products_equal_independent_kernels"]:
        raise AssertionError("transfer target drift")
    self_inverse, pairs = inversion_orbits()
    if len(self_inverse) != 3 or len(pairs) != 16:
        raise AssertionError((self_inverse, pairs))
    first = formal_assignment(distinguished=Fraction(1))
    second = formal_assignment(distinguished=Fraction(2))
    check_assignment(first)
    check_assignment(second)
    if first[(0, 1)] ** 2 == second[(0, 1)] ** 2:
        raise AssertionError("countermodels did not separate a packet square")
    signed_pairs = []
    for left, right in pairs:
        _, sign = standard_negative(left)
        signed_pairs.append({"left": list(left), "right": list(right), "product_sign": sign})
    return {
        "schema": "sic-stark-cycle-186-normalized-afk-packet-prototype-v2",
        "epistemic_status": "PROVED",
        "claim_boundary": "This correction concerns only the finite relation quotient generated by the stated AFK normalized-overlap definition, its proved reciprocal theorem after exact even-d standard-representative quasiperiodicity, the canonical zero relation, and the sealed multiplier transfer. It makes no assertion that analytic modular-cocycle values are arbitrary or that no further analytic AFK relation exists.",
        "correction": {"supersedes": "cycle-186-normalized-afk-packet-v1", "error": "v1 imposed u_p*u_reduce(-p)=1 on standard representatives and omitted the even-d quasiperiodic sign.", "cause": "The source reciprocal theorem is for integer p and -p; for a standard representative r=reduce(-p), AFK Lemma lem:nupperiodicity gives u_p*u_r=(-1)^<q,p>, where r=-p+6q.", "affected_claims": ["v1's all-ones background countermodel", "v1's stated standard-representative relation"], "unaffected_after_rerun": ["36/35/3/16 census", "finite underdetermination of u_(0,1)^2", "independence of multiplier and transfer labels"]},
        "primary_source": {"paper": "Appleby--Flammia--Kopp arXiv:2501.03970v2", "source_sha256": "93a9f24403d761e29c019d0ad290d3fd8beba1bbf9d6834010639d3b04306e2d", "definition": "Definition 1.32 / dfn:GhostOverlaps", "theorem": "Theorem 5.8 / thm:nupnumpeq1: nu_p nu_-p=1 for integer p not congruent zero", "quasiperiodicity": "Lemma lem:nupperiodicity", "zero_relation": "Lemma 5.9 / lem:nu01overnu0val"},
        "formal_packet": {"domain": "(Z/6Z)^2 standard representatives", "nonzero_generator_count": 35, "relations": "u_p*u_reduce(-p)=(-1)^<q,p> when reduce(-p)=-p+6q", "self_inverse_nonzero": [list(point) for point in self_inverse], "signed_free_inverse_pairs": signed_pairs, "free_multiplicative_rank": len(pairs), "zero_polynomial": "x^2+4sqrt(7)x+1=0"},
        "countermodels": {"first": {"u_(0,1)": "1", "u_(0,5)": "1"}, "second": {"u_(0,1)": "2", "u_(0,5)": "1/2"}, "all_other_nonzero_u": "canonical signed-reciprocal assignment", "common_zero_relation": True, "common_multiplier_ledger": True, "common_transfer_labels": True, "separating_observable": "u_(0,1)^2: 1 versus 4"},
        "summary": {"packet_characteristics_checked": 36, "nonzero_characteristics_checked": 35, "self_inverse_nonzero_count": len(self_inverse), "free_inverse_pair_count": len(pairs), "free_multiplicative_rank": len(pairs), "multiplier_records_checked": len(multiplier["records"]), "transfer_label_count": transfer["summary"]["relation_label_count"], "countermodels_checked": 2, "finite_relation_data_determines_u_01_square": False},
        "gate_outcome": {"normalized_afk_packet": "FINITE_RELATION_UNDERDETERMINATION_PROVED_AFTER_EVEN_D_CONVENTION_CORRECTION", "scope": "the corrected finite relation system only; analytic modular-cocycle evaluation remains the missing data"},
    }


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", type=Path)
    args = parser.parse_args()
    rendered = json.dumps(payload(), indent=2, sort_keys=True) + "\n"
    if args.output:
        args.output.write_text(rendered)
    else:
        print(rendered, end="")


if __name__ == "__main__":
    main()
