#!/usr/bin/env python3
"""Exact finite-relation audit for the normalized AFK d=6 packet."""
from __future__ import annotations

import argparse
from fractions import Fraction
import json
from pathlib import Path
import subprocess
import sys


ROOT = Path(__file__).resolve().parents[1]
TRANSFER = ROOT / "discovery/cycle-185-multiplier-weighted-relation-transfer-prototype-v1.json"
MULTIPLIER = ROOT / "scripts/dimension_six_stabilizer_ledger.py"
Point = tuple[int, int]


def negative(point: Point) -> Point:
    return (-point[0]) % 6, (-point[1]) % 6


def inversion_orbits() -> tuple[list[Point], list[tuple[Point, Point]]]:
    self_inverse = []
    pairs = []
    for point in ((a, b) for a in range(6) for b in range(6) if (a, b) != (0, 0)):
        inverse = negative(point)
        if point == inverse:
            self_inverse.append(point)
        elif point < inverse:
            pairs.append((point, inverse))
    return self_inverse, pairs


def formal_assignment(*, distinguished: Fraction) -> dict[Point, Fraction]:
    values = {point: Fraction(1) for point in ((a, b) for a in range(6) for b in range(6) if (a, b) != (0, 0))}
    values[(0, 1)] = distinguished
    values[(0, 5)] = Fraction(1, 1) / distinguished
    return values


def check_assignment(values: dict[Point, Fraction]) -> None:
    if set(values) != {(a, b) for a in range(6) for b in range(6)} - {(0, 0)}:
        raise AssertionError("assignment support")
    for point, value in values.items():
        if not value:
            raise AssertionError(("zero nonzero-overlap", point))
        if value * values[negative(point)] != 1:
            raise AssertionError(("reciprocal relation", point))


def payload() -> dict[str, object]:
    multiplier = json.loads(subprocess.run([sys.executable, str(MULTIPLIER)], check=True, capture_output=True, text=True, timeout=10).stdout)
    transfer = json.loads(TRANSFER.read_text())
    if not (multiplier["all_36_characteristics_fixed"] and multiplier["all_multiplier_comparisons_match"]):
        raise AssertionError("multiplier ledger drift")
    if transfer["summary"]["relation_label_count"] != 11 or not transfer["summary"]["all_triple_products_equal_independent_kernels"]:
        raise AssertionError("transfer target drift")

    self_inverse, pairs = inversion_orbits()
    if len(self_inverse) != 3 or len(pairs) != 16:
        raise AssertionError((self_inverse, pairs))
    first = formal_assignment(distinguished=Fraction(1))
    second = formal_assignment(distinguished=Fraction(2))
    check_assignment(first)
    check_assignment(second)
    if first[(0, 1)] ** 2 == second[(0, 1)] ** 2:
        raise AssertionError("countermodels did not separate a packet square")
    return {
        "schema": "sic-stark-cycle-186-normalized-afk-packet-prototype-v1",
        "epistemic_status": "PROVED",
        "claim_boundary": "This exact formal result concerns only the finite relation quotient generated by the stated AFK normalized-overlap definition, its proved reciprocal theorem, the canonical zero relation, and the sealed multiplier transfer. It makes no assertion that the analytic modular-cocycle values are arbitrary or that no further analytic AFK relation exists.",
        "primary_source": {"paper": "Appleby--Flammia--Kopp arXiv:2501.03970v2", "definition": "Definition 1.32 / dfn:GhostOverlaps: nu_p=Phi_p shin_A^(p/d)(rho)", "theorem": "Theorem 5.8 / thm:nupnumpeq1: nu_p nu_-p=1 for p nonzero", "zero_relation": "Lemma 5.9 / lem:nu01overnu0val: nu_0+nu_0^-1=-4sqrt(7) in canonical d=6"},
        "formal_packet": {"domain": "(Z/6Z)^2 standard representatives", "nonzero_generator_count": 35, "relations": "u_p u_-p=1", "self_inverse_nonzero": [list(point) for point in self_inverse], "free_inverse_pairs": [[list(left), list(right)] for left, right in pairs], "free_multiplicative_rank": len(pairs), "zero_polynomial": "x^2+4sqrt(7)x+1=0", "zero_roots": "-2sqrt(7) +/- 3sqrt(3)"},
        "countermodels": {"first": {"u_(0,1)": "1", "u_(0,5)": "1"}, "second": {"u_(0,1)": "2", "u_(0,5)": "1/2"}, "all_other_nonzero_u": "1", "common_zero_relation": True, "common_multiplier_ledger": True, "common_transfer_labels": True, "separating_observable": "u_(0,1)^2: 1 versus 4"},
        "summary": {"packet_characteristics_checked": 36, "nonzero_characteristics_checked": 35, "self_inverse_nonzero_count": len(self_inverse), "free_inverse_pair_count": len(pairs), "free_multiplicative_rank": len(pairs), "multiplier_records_checked": len(multiplier["records"]), "transfer_label_count": transfer["summary"]["relation_label_count"], "countermodels_checked": 2, "finite_relation_data_determines_u_01_square": False},
        "gate_outcome": {"normalized_afk_packet": "FINITE_RELATION_UNDERDETERMINATION_PROVED", "scope": "the stated finite relation system only; analytic modular-cocycle evaluation remains the missing data"},
    }


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", type=Path)
    args = parser.parse_args()
    rendered = json.dumps(payload(), indent=2, sort_keys=True) + "\n"
    if args.output:
        args.output.write_text(rendered)
    else:
        print(rendered, end="")


if __name__ == "__main__":
    main()
