#!/usr/bin/env python3
"""Measure how sectorwise reciprocity changes the F_4 residual census.

Residual families are first canonicalized under independent rotations
and input/output exchange, as in the original scan.  This script then
computes the larger closure generated by:

* independent rotations and reflections of input and output modes;
* input/output exchange;
* the proved odd-sector histogram reciprocity.

It reports both the number of resulting closure components and whether
a nominally residual family reaches an event caught directly by the
elementary cyclic rule.
"""

from __future__ import annotations

import argparse
import sys
from collections import deque
from functools import lru_cache
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from src.fourier_suppression import (  # noqa: E402
    canonical_dark_pair,
    four_mode_odd_sector_reciprocal_pair,
    is_dark_prime_power,
    occupation_vectors,
    simple_cyclic_rule_predicts_dark,
)


Occupation = tuple[int, int, int, int]
Pair = tuple[Occupation, Occupation]


def rotate(occupation: Occupation, amount: int) -> Occupation:
    return occupation[amount:] + occupation[:amount]


def reflect(occupation: Occupation) -> Occupation:
    return occupation[:1] + tuple(reversed(occupation[1:]))


@lru_cache(maxsize=None)
def dihedral_images(occupation: Occupation) -> tuple[Occupation, ...]:
    images = set()
    for amount in range(4):
        rotated = rotate(occupation, amount)
        images.add(rotated)
        images.add(reflect(rotated))
    return tuple(sorted(images))


def elementary_images(pair: Pair) -> set[Pair]:
    input_occupation, output_occupation = pair
    images = {
        (input_image, output_image)
        for input_image in dihedral_images(input_occupation)
        for output_image in dihedral_images(output_occupation)
    }
    return images | {
        (output_image, input_image)
        for input_image, output_image in images
    }


def reciprocity_orbit(pair: Pair) -> tuple[set[Pair], bool]:
    """Return the full generated orbit and whether it contains a cyclic event."""
    seen: set[Pair] = set()
    queue = deque([pair])
    contains_direct_cyclic = False

    while queue:
        current = queue.popleft()
        if current in seen:
            continue
        seen.add(current)

        if simple_cyclic_rule_predicts_dark(*current):
            contains_direct_cyclic = True

        for image in elementary_images(current):
            if image not in seen:
                queue.append(image)

        reciprocal = four_mode_odd_sector_reciprocal_pair(*current)
        if reciprocal is not None and reciprocal not in seen:
            queue.append(reciprocal)

    return seen, contains_direct_cyclic


def residual_families(particles: int) -> set[Pair]:
    occupations = list(occupation_vectors(particles, 4))
    residual = set()
    for input_occupation in occupations:
        for output_occupation in occupations:
            if not is_dark_prime_power(
                input_occupation, output_occupation
            ):
                continue
            if simple_cyclic_rule_predicts_dark(
                input_occupation, output_occupation
            ):
                continue
            residual.add(
                canonical_dark_pair(input_occupation, output_occupation)
            )
    return residual


def analyze(particles: int) -> tuple[int, int, int]:
    residual = residual_families(particles)
    components: set[Pair] = set()
    reaches_cyclic = 0
    for pair in residual:
        orbit, contains_direct_cyclic = reciprocity_orbit(pair)
        components.add(min(orbit))
        if contains_direct_cyclic:
            reaches_cyclic += 1
    return len(residual), len(components), reaches_cyclic


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--min-particles", type=int, default=4)
    parser.add_argument("--max-particles", type=int, default=9)
    args = parser.parse_args()
    if args.min_particles < 0:
        parser.error("--min-particles must be nonnegative")
    if args.max_particles < args.min_particles:
        parser.error("--max-particles must be at least --min-particles")

    print("N  residual  closure-components  residual-reaching-cyclic")
    for particles in range(
        args.min_particles, args.max_particles + 1
    ):
        residual, components, reaches_cyclic = analyze(particles)
        print(
            f"{particles:2d} {residual:9d} "
            f"{components:19d} {reaches_cyclic:24d}"
        )


if __name__ == "__main__":
    main()
