\\ Exact arithmetic certificate for the two quartic character pairs in the
\\ canonical dimension-eight order-ray packet.

default(realprecision, 100);
default(parisizemax, 4000000000);

assert_equal(label, actual, expected) =
{
  if(actual != expected,
    error(Str(label, ": expected ", expected, ", got ", actual)));
  print(label, "=", actual);
};

assert_small(label, actual, tolerance) =
{
  if(abs(actual) > tolerance,
    error(Str(label, ": residual ", actual, " exceeds ", tolerance)));
  print(label, "=", actual);
};

even_polynomial_in_square(value, source_polynomial, target_variable) =
{
  my(reduced = lift(Mod(value, source_polynomial)));
  my(result = 0);
  for(k = 0, poldegree(reduced),
    if(k % 2,
      if(polcoef(reduced, k) != 0,
        error(Str("odd coefficient survives at degree ", k))),
      result += polcoef(reduced, k) * target_variable^(k/2)));
  result;
};

unit_exponent_matrix(field_bnf, unit_list) =
{
  my(rank = field_bnf.r1 + field_bnf.r2 - 1);
  matrix(rank, #unit_list, row, col,
    bnfisunit(field_bnf, unit_list[col])[row]);
};

maximal_minor_gcd(matrix_value) =
{
  my(rank = matsize(matrix_value)[1]);
  my(columns = matsize(matrix_value)[2]);
  my(result = 0);
  for(i = 1, columns,
    for(j = i + 1, columns,
      for(k = j + 1, columns,
        if(rank == 3,
          result = gcd(result,
            abs(matdet(vecextract(matrix_value, [1, 2, 3], [i, j, k]))))))));
  result;
};

K = bnfinit(y^2 - y - 1, 1);
one_infinite_place = [1, 0];
ray8 = bnrinit(K, [8, one_infinite_place], 1);
ray24 = bnrinit(K, [24, one_infinite_place], 1);

print("PARI_VERSION=", version());
assert_equal("BASE_CLASS_NUMBER", K.no, 1);
assert_equal("BASE_BNFCERTIFY", bnfcertify(K), 1);
assert_equal("MAXIMAL_RAY_8_STRUCTURE", ray8.cyc, [2, 2]);
assert_equal("MAXIMAL_RAY_24_STRUCTURE", ray24.cyc, [4, 2, 2]);
print("QUARTIC_CONDUCTOR_0=", bnrconductor(ray24, [1, 0, 0]));
print("QUARTIC_CONDUCTOR_1=", bnrconductor(ray24, [1, 1, 0]));
print("COMMON_QUADRATIC_CONDUCTOR=", bnrconductor(ray24, [2, 0, 0]));

phi = Mod(y, y^2 - y - 1);
lift_A = 8 + 3*phi;
lift_B = 17 + 12*phi;
lift_R = 7;
log_A = bnrisprincipal(ray24, idealhnf(K, lift_A), 0);
log_B = bnrisprincipal(ray24, idealhnf(K, lift_B), 0);
log_R = bnrisprincipal(ray24, idealhnf(K, lift_R), 0);
assert_equal("ORDER_C4_GENERATOR_MAXIMAL_RAY_LOG", log_A, [1, 1, 0]~);
assert_equal("ORDER_C2_GENERATOR_MAXIMAL_RAY_LOG", log_B, [0, 1, 0]~);
assert_equal("ORDER_SIGN_CLASS_MAXIMAL_RAY_LOG", log_R, [2, 0, 1]~);

\\ The order O_3 = Z + 3 O_K has (8 O_3 : O_K) = 24 O_K.  The order-ray
\\ group has structure C4 x C2 x C2, so the Kopp--Lagarias surjection
\\ Cl_(24,infinity)(O_K) -> Cl_(8,infinity)(O_3) is an isomorphism.

\\ Quotient fields for the two quartic character pairs [1,b,0], b=0,1,
\\ in PARI's ray24 dual coordinates.
H0 = Mat([4, 0, 0; 0, 1, 0; 0, 0, 1]);
H1 = Mat([4, 2, 0; 0, 1, 0; 0, 0, 1]);

relative0 = bnrclassfield(ray24, H0, 1);
relative1 = bnrclassfield(ray24, H1, 1);
absolute0 = rnfpolredbest(K, relative0, 2);
absolute1 = rnfpolredbest(K, relative1, 2);
F0 = bnfinit(absolute0, 1);
F1 = bnfinit(absolute1, 1);

print("QUARTIC_RELATIVE_POLYNOMIAL_0=", relative0);
print("QUARTIC_RELATIVE_POLYNOMIAL_1=", relative1);
print("QUARTIC_RELATIVE_DISCRIMINANT_0=", \
  idealfactor(K, rnfdisc(K, relative0)[1]));
print("QUARTIC_RELATIVE_DISCRIMINANT_1=", \
  idealfactor(K, rnfdisc(K, relative1)[1]));
print("QUARTIC_ABSOLUTE_POLYNOMIAL_0=", absolute0);
print("QUARTIC_ABSOLUTE_POLYNOMIAL_1=", absolute1);
assert_equal("QUARTIC_SIGNATURE_0", F0.sign, [4, 2]);
assert_equal("QUARTIC_SIGNATURE_1", F1.sign, [4, 2]);
assert_equal("QUARTIC_CLASS_NUMBER_0", F0.no, 1);
assert_equal("QUARTIC_CLASS_NUMBER_1", F1.no, 1);
assert_equal("QUARTIC_BNFCERTIFY_0", bnfcertify(F0), 1);
assert_equal("QUARTIC_BNFCERTIFY_1", bnfcertify(F1), 1);

\\ Both quartic quotients have the same quadratic fixed field over K.
common_relative = x^2 - 3;
common_absolute = rnfpolredbest(K, common_relative, 2);
common_field = bnfinit(common_absolute, 1);
print("COMMON_QUADRATIC_RELATIVE_POLYNOMIAL=", common_relative);
print("COMMON_QUADRATIC_ABSOLUTE_POLYNOMIAL=", common_absolute);
assert_equal("COMMON_QUADRATIC_SIGNATURE", common_field.sign, [4, 0]);
assert_equal("COMMON_QUADRATIC_CLASS_NUMBER", common_field.no, 1);
assert_equal("COMMON_QUADRATIC_BNFCERTIFY", bnfcertify(common_field), 1);

\\ Work in the especially transparent absolute models produced by PARI.
P0 = x^8 - 6*x^6 - 30*x^4 - 18*x^2 + 9;
P1 = x^8 + 6*x^6 - 30*x^4 + 18*x^2 + 9;
assert_equal("MODEL_0_ISOMORPHIC", #nfisisom(nfinit(absolute0), P0) > 0, 1);
assert_equal("MODEL_1_ISOMORPHIC", #nfisisom(nfinit(absolute1), P1) > 0, 1);
M0 = bnfinit(P0, 1);
M1 = bnfinit(P1, 1);

\\ In both models tau(x)=-x is the order-two automorphism.  Its fixed
\\ field is generated by t=x^2.
Q0 = t^4 - 6*t^3 - 30*t^2 - 18*t + 9;
Q1 = t^4 + 6*t^3 - 30*t^2 + 18*t + 9;
E0 = bnfinit(Q0, 1);
E1 = bnfinit(Q1, 1);
assert_equal("FIXED_FIELD_0_IS_COMMON", #nfisisom(E0, common_field) > 0, 1);
assert_equal("FIXED_FIELD_1_IS_COMMON", #nfisisom(E1, common_field) > 0, 1);

\\ Compute the full norm images U_F -> U_E.  The gcd of the maximal
\\ minors of the exponent matrix is [U_E : N(U_F)].
norm_units0 = vector(#M0.fu, j, \
  Mod(even_polynomial_in_square( \
    lift(M0.fu[j]) * subst(lift(M0.fu[j]), x, -x), P0, t), Q0));
norm_units1 = vector(#M1.fu, j, \
  Mod(even_polynomial_in_square( \
    lift(M1.fu[j]) * subst(lift(M1.fu[j]), x, -x), P1, t), Q1));
norm_matrix0 = unit_exponent_matrix(E0, norm_units0);
norm_matrix1 = unit_exponent_matrix(E1, norm_units1);
print("NORM_UNIT_EXPONENT_MATRIX_0=", norm_matrix0);
print("NORM_UNIT_EXPONENT_MATRIX_1=", norm_matrix1);
norm_index0 = maximal_minor_gcd(norm_matrix0);
norm_index1 = maximal_minor_gcd(norm_matrix1);
assert_equal("RELATIVE_UNIT_NORM_INDEX_0", norm_index0, 4);
assert_equal("RELATIVE_UNIT_NORM_INDEX_1", norm_index1, 4);

\\ Candidate anti-units.  PARI orders the five free generators so that
\\ the product of the fourth and fifth, squared, is Roblot's unit.
eta0 = (M0.fu[4] * M0.fu[5])^2;
eta1 = (M1.fu[4] * M1.fu[5])^2;
assert_equal("ANTI_UNIT_IDENTITY_0", \
  Mod(lift(eta0) * subst(lift(eta0), x, -x), P0), Mod(1, P0));
assert_equal("ANTI_UNIT_IDENTITY_1", \
  Mod(lift(eta1) * subst(lift(eta1), x, -x), P1), Mod(1, P1));
print("ETA_0=", eta0);
print("ETA_1=", eta1);
print("ETA_MINPOLY_0=", minpoly(eta0));
print("ETA_MINPOLY_1=", minpoly(eta1));

\\ The relative anti-unit lattice has rank two.  The two conjugates of
\\ eta generate an index-four sublattice, the value required by Roblot's
\\ formula because e=2, t_S=0, and the relative class group is trivial.
conjugates0 = nfgaloisconj(P0);
conjugates1 = nfgaloisconj(P1);
sigma0 = conjugates0[3];
sigma1 = conjugates1[3];
assert_equal("SIGMA_SQUARED_IS_TAU_0", \
  Mod(subst(sigma0, x, sigma0), P0), Mod(-x, P0));
assert_equal("SIGMA_SQUARED_IS_TAU_1", \
  Mod(subst(sigma1, x, sigma1), P1), Mod(-x, P1));

eta_sigma0 = Mod(subst(lift(eta0), x, sigma0), P0);
eta_sigma1 = Mod(subst(lift(eta1), x, sigma1), P1);
eta_exponents0 = unit_exponent_matrix(M0, [eta0, eta_sigma0]);
eta_exponents1 = unit_exponent_matrix(M1, [eta1, eta_sigma1]);
print("ETA_CONJUGATE_EXPONENT_MATRIX_0=", eta_exponents0);
print("ETA_CONJUGATE_EXPONENT_MATRIX_1=", eta_exponents1);

sigma_units0 = vector(#M0.fu, j, \
  Mod(subst(lift(M0.fu[j]), x, sigma0), P0));
sigma_units1 = vector(#M1.fu, j, \
  Mod(subst(lift(M1.fu[j]), x, sigma1), P1));
sigma_matrix0 = unit_exponent_matrix(M0, sigma_units0);
sigma_matrix1 = unit_exponent_matrix(M1, sigma_units1);
tau_matrix0 = sigma_matrix0^2;
tau_matrix1 = sigma_matrix1^2;
anti_lattice0 = matkerint(matid(5) + tau_matrix0);
anti_lattice1 = matkerint(matid(5) + tau_matrix1);
eta_coordinates0 = matinverseimage(anti_lattice0, eta_exponents0);
eta_coordinates1 = matinverseimage(anti_lattice1, eta_exponents1);
print("SIGMA_UNIT_MATRIX_0=", sigma_matrix0);
print("SIGMA_UNIT_MATRIX_1=", sigma_matrix1);
print("ANTI_UNIT_LATTICE_0=", anti_lattice0);
print("ANTI_UNIT_LATTICE_1=", anti_lattice1);
print("ETA_ANTI_LATTICE_COORDINATES_0=", eta_coordinates0);
print("ETA_ANTI_LATTICE_COORDINATES_1=", eta_coordinates1);
assert_equal("ROBLOT_UNIT_INDEX_0", abs(matdet(eta_coordinates0)), 4);
assert_equal("ROBLOT_UNIT_INDEX_1", abs(matdet(eta_coordinates1)), 4);

\\ Numerical checks against PARI's primitive and imprimitive L derivatives.
L_imprimitive = bnrL1(ray24, , 6);
L_primitive = bnrL1(ray24, , 4);
quartic_characters = [[1,0,0], [3,0,0], [1,1,0], [3,1,0]];
for(j = 1, #quartic_characters, \
{
  my(character = quartic_characters[j]);
  my(index_imprimitive);
  my(index_primitive);
  for(k = 1, #L_imprimitive, \
    if(L_imprimitive[k][1] == character, index_imprimitive = k));
  for(k = 1, #L_primitive, \
    if(L_primitive[k][1] == character, index_primitive = k));
  print(Str("QUARTIC_L_DERIVATIVE_", character), "=", \
    L_primitive[index_primitive][2][2]);
  assert_small(Str("EULER_FACTOR_RESIDUAL_", character), \
    L_imprimitive[index_imprimitive][2][2] \
      / L_primitive[index_primitive][2][2] - 1, \
    1e-80);
});

print("ETA_REAL_LOGS_0=", vector(4, j, log(abs(nfeltembed(M0, eta0, j)))));
print("ETA_REAL_LOGS_1=", vector(4, j, log(abs(nfeltembed(M1, eta1, j)))));

target0 = 0;
target1 = 0;
for(k = 1, #L_primitive, \
{
  if(L_primitive[k][1] == [1, 0, 0], target0 = L_primitive[k][2][2]);
  if(L_primitive[k][1] == [1, 1, 0], target1 = L_primitive[k][2][2]);
});
logs0 = vector(4, j, log(abs(nfeltembed(M0, eta0, j))));
logs1 = vector(4, j, log(abs(nfeltembed(M1, eta1, j))));
resolvent0 = logs0[3] + I * logs0[4];
resolvent1 = logs1[2] + I * logs1[1];
assert_small("ROBLOT_ABSOLUTE_VALUE_RESIDUAL_0", \
  abs(resolvent0) - abs(target0), 1e-80);
assert_small("ROBLOT_ABSOLUTE_VALUE_RESIDUAL_1", \
  abs(resolvent1) - abs(target1), 1e-80);
\\ These phase residuals are evidence, not an unconditional consequence of
\\ Roblot's Theorem 6.1, whose conclusion contains absolute values.
assert_small("NUMERICAL_PHASE_RESIDUAL_0", \
  resolvent0 - target0, 1e-80);
assert_small("NUMERICAL_PHASE_RESIDUAL_1", \
  resolvent1 - target1, 1e-80);

quit();
