\\ Direct Roblot-P1 audit for the wild dimension-six ray field.
\\
\\ Roblot's tame sextic hypotheses are sufficient conditions for the
\\ existence of a P1/P2 unit.  Proposition 4.1 itself only needs an
\\ explicit anti-unit satisfying P1.  This script tests the certified
\\ candidate eta=x^2 directly.

default(realprecision, 100);
default(parisizemax, 4000000000);

assert_equal(label, actual, expected) =
{
  if(actual != expected,
    error(Str(label, ": expected ", expected, ", got ", actual)));
  print(label, "=", actual);
};

unit_exponent_matrix(field_bnf, unit_list) =
{
  my(rank = field_bnf.r1 + field_bnf.r2 - 1);
  matrix(rank, #unit_list, row, col,
    bnfisunit(field_bnf, unit_list[col])[row]);
};

maximal_minor_gcd(matrix_value) =
{
  my(rank = matsize(matrix_value)[1]);
  my(columns = matsize(matrix_value)[2]);
  my(result = 0);
  forvec(indices = vector(rank, j, [1, columns]),
    if(#Set(indices) == rank,
      result = gcd(result,
        abs(matdet(vecextract(
          matrix_value, vector(rank, j, j), indices))))),
    1);
  result;
};

Q = x^12 + 3*x^11 - 6*x^10 - 16*x^9 + 3*x^8 + 27*x^6 \
  + 3*x^4 - 16*x^3 - 6*x^2 + 3*x + 1;
L = bnfinit(Q, 1);
alpha = Mod(x, Q);
automorphisms = nfgaloisconj(L);

\\ Arithmetic Frobenius from the separate orientation certificate.
sigma_gen = Mod(automorphisms[5], Q);
sigma2 = Mod(subst(lift(sigma_gen), x, lift(sigma_gen)), Q);
tau_image = Mod(subst(lift(sigma2), x, lift(sigma_gen)), Q);
assert_equal("TAU_ORDER_TWO", \
  Mod(subst(lift(tau_image), x, lift(tau_image)), Q), alpha);
assert_equal("TAU_IMAGE_OF_ALPHA", tau_image, Mod(1/x, Q));

\\ The tau-fixed field is generated by s=alpha+alpha^-1.
s_in_L = alpha + alpha^-1;
Epol = subst(minpoly(s_in_L), x, t);
E = bnfinit(Epol, 1);

\\ Convert a tau-fixed element of L to the power basis of E.
fixed_basis_matrix = matrix(12, 6, i, j, \
  polcoef(lift(s_in_L^(j-1)), i-1));
fixed_preimage(value) =
{
  my(target, coordinates, result = 0);
  target = vector(12, row, polcoef(lift(value), row-1))~;
  coordinates = matinverseimage(fixed_basis_matrix, target);
  for(j = 1, 6, result += coordinates[j]*t^(j-1));
  Mod(result, Epol);
};

print("PARI_VERSION=", version());
print("RAY_FIELD_POLYNOMIAL=", Q);
print("TOTALLY_REAL_FIXED_FIELD_POLYNOMIAL=", Epol);
assert_equal("RAY_FIELD_SIGNATURE", L.sign, [6, 3]);
assert_equal("FIXED_FIELD_SIGNATURE", E.sign, [6, 0]);
print("RAY_FIELD_CLASS_NUMBER=", L.no);
print("FIXED_FIELD_CLASS_NUMBER=", E.no);
assert_equal("RAY_FIELD_BNFCERTIFY", bnfcertify(L), 1);
assert_equal("FIXED_FIELD_BNFCERTIFY", bnfcertify(E), 1);

\\ Compute [U_E : N(U_L)]=2^e.
norm_unit(unit) =
{
  my(tau_unit = Mod(subst(lift(unit), x, lift(tau_image)), Q));
  my(norm_unit = unit*tau_unit);
  if(Mod(subst(lift(norm_unit), x, lift(tau_image)), Q) != norm_unit,
    error("unit norm is not tau-fixed"));
  fixed_preimage(norm_unit);
};
norm_units = vector(#L.fu, j, norm_unit(L.fu[j]));
norm_matrix = unit_exponent_matrix(E, norm_units);
norm_index = maximal_minor_gcd(norm_matrix);
print("NORM_UNIT_EXPONENT_MATRIX=", norm_matrix);
print("RELATIVE_UNIT_NORM_INDEX=", norm_index);

\\ Compute U_L^- and the index of eta,eta^(gamma^2),eta^(gamma^4).
sigma_units = vector(#L.fu, j, \
  Mod(subst(lift(L.fu[j]), x, lift(sigma_gen)), Q));
sigma_matrix = unit_exponent_matrix(L, sigma_units);
tau_matrix = sigma_matrix^3;
anti_lattice = matkerint(matid(#L.fu) + tau_matrix);
candidate = alpha^2;
candidate_sigma2 = \
  Mod(subst(lift(candidate), x, lift(sigma2)), Q);
sigma4 = Mod(subst(lift(sigma2), x, lift(sigma2)), Q);
candidate_sigma4 = \
  Mod(subst(lift(candidate), x, lift(sigma4)), Q);
assert_equal("ETA_ANTI_UNIT_IDENTITY", \
  candidate*Mod(subst(lift(candidate), x, lift(tau_image)), Q), Mod(1, Q));
eta_exponents = unit_exponent_matrix( \
  L, [candidate, candidate_sigma2, candidate_sigma4]);
eta_coordinates = matinverseimage(anti_lattice, eta_exponents);
eta_index = abs(matdet(eta_coordinates));
print("GAMMA_UNIT_MATRIX=", sigma_matrix);
print("ANTI_UNIT_LATTICE=", anti_lattice);
print("ETA_CONJUGATE_EXPONENT_MATRIX=", eta_exponents);
print("ETA_ANTI_LATTICE_COORDINATES=", eta_coordinates);
print("ROBLOT_CANDIDATE_INDEX=", eta_index);

\\ For this ray extension the finite ramified primes are above 2 and 3.
\\ t_S is computed separately from relative splitting.  P1 predicts
\\ index = 2^(e+t_S) * h_L/h_E.
class_number_minus = L.no/E.no;
e_exponent = valuation(norm_index, 2);
print("RELATIVE_CLASS_NUMBER=", class_number_minus);
print("NORM_INDEX_TWO_EXPONENT=", e_exponent);
print("P1_REQUIRED_T_S=", \
  valuation(eta_index/class_number_minus, 2) - e_exponent);

\\ Count primes of the totally real field in S={infinity,2,3} that
\\ are inert in the quadratic top step L/E.
relative_variable = varhigher("relative_variable", t);
relative_polynomial = \
  relative_variable^2-Mod(t, Epol)*relative_variable+1;
relative_extension = rnfinit(E, relative_polynomial);
decomposition_two = rnfidealprimedec(relative_extension, 2);
decomposition_three = rnfidealprimedec(relative_extension, 3);
print("TOP_QUADRATIC_RELATIVE_POLYNOMIAL=", relative_polynomial);
print("TOP_STEP_DECOMPOSITION_AT_TWO=", decomposition_two);
print("TOP_STEP_DECOMPOSITION_AT_THREE=", decomposition_three);

\\ There is one E-prime above each rational prime.  At 2 its absolute
\\ ramification index stays 3 while its residue degree doubles 2->4:
\\ it is inert in L/E.  At 3 the residue degree stays 1 while the
\\ ramification index doubles 6->12: it is ramified, not inert.
assert_equal("E_PRIMES_ABOVE_TWO", #decomposition_two[1], 1);
assert_equal("L_PRIMES_ABOVE_E_PRIME_TWO", #decomposition_two[2][1], 1);
assert_equal("TWO_TOP_STEP_RAMIFICATION_RATIO", \
  decomposition_two[2][1][1][3] \
    / decomposition_two[1][1][3], 1);
assert_equal("TWO_TOP_STEP_RESIDUE_DEGREE_RATIO", \
  decomposition_two[2][1][1][4] \
    / decomposition_two[1][1][4], 2);
assert_equal("E_PRIMES_ABOVE_THREE", #decomposition_three[1], 1);
assert_equal("L_PRIMES_ABOVE_E_PRIME_THREE", \
  #decomposition_three[2][1], 1);
assert_equal("THREE_TOP_STEP_RAMIFICATION_RATIO", \
  decomposition_three[2][1][1][3] \
    / decomposition_three[1][1][3], 2);
assert_equal("THREE_TOP_STEP_RESIDUE_DEGREE_RATIO", \
  decomposition_three[2][1][1][4] \
    / decomposition_three[1][1][4], 1);
t_S = 1;
assert_equal("ROBLOT_T_S", t_S, 1);
assert_equal("ROBLOT_P1_RIGHT_HAND_SIDE", \
  2^(e_exponent+t_S)*class_number_minus, eta_index);
print("ROBLOT_P1_CERTIFIED=1");

quit();
