\\ Exact arithmetic audit showing why d=7 is the next unconditional
\\ SIC--Stark candidate.

default(parisizemax, 4000000000);

assert_equal(label, actual, expected) =
{
  if(actual != expected,
    error(Str(label, ": expected ", expected, ", got ", actual)));
  print(label, "=", actual);
};

K = bnfinit(y^2 - 2, 1);
sqrt_two = Mod(y, y^2 - 2);
phi = 1 + sqrt_two;
beta = phi^2;

print("PARI_VERSION=", version());
assert_equal("BASE_DISCRIMINANT", K.disc, 8);
assert_equal("BASE_CLASS_NUMBER", K.no, 1);
assert_equal("BASE_BNFCERTIFY", bnfcertify(K), 1);
assert_equal("BETA_POLYNOMIAL", minpoly(beta), x^2 - 6*x + 1);
assert_equal("CANONICAL_ORDER_DISCRIMINANT", 4*K.disc, 32);
assert_equal("CANONICAL_ORDER_CLASS_NUMBER", qfbclassno(32), 1);
print("CANONICAL_ORDER=Z+2*O_K");
print("CANONICAL_ORDER_UNIT_GROUP=<-1,beta>");
print("MULTIPLIER_IDEAL_OF_7O=14*O_K");

ray14_one = bnrinit(K, [14, [1, 0]], 1);
ray14_both = bnrinit(K, [14, [1, 1]], 1);
ray7_one = bnrinit(K, [7, [1, 0]], 1);
ray7_both = bnrinit(K, [7, [1, 1]], 1);

assert_equal("RAY_14_ONE_STRUCTURE", ray14_one.cyc, [6, 2]);
assert_equal("RAY_14_BOTH_STRUCTURE", ray14_both.cyc, [6, 2, 2]);
assert_equal("RAY_7_ONE_STRUCTURE", ray7_one.cyc, [6]);
assert_equal("RAY_7_BOTH_STRUCTURE", ray7_both.cyc, [6, 2]);

\\ Direct local order calculation:
\\ |(O/7O)^x|=36, the sign factor has order 2, and the image of
\\ <-1,beta> has order 6.  Since Pic(O)=1, the order ray group has
\\ order 36*2/6=12, equal to the maximal ray-14 group.  The natural
\\ Kopp--Lagarias map is therefore an isomorphism.
residue_unit_group_order = 0;
for(a = 0, 6, for(b = 0, 6, \
  if(gcd((a^2 + 6*a*b + b^2) % 7, 7) == 1, \
    residue_unit_group_order++)));
assert_equal("ORDER_RESIDUE_UNIT_GROUP_ORDER", \
  residue_unit_group_order, 36);

\\ beta has exact order three modulo 7, and adjoining the signed image
\\ of -1 doubles the image.
beta_mod_seven = Mod(x, Mod(1, 7)*(x^2 - 6*x + 1));
assert_equal("BETA_CUBED_MOD_7", beta_mod_seven^3, 1);
assert_equal("BETA_NONTRIVIAL_MOD_7", beta_mod_seven == 1, 0);
order_global_unit_image = 3*2;
assert_equal("ORDER_GLOBAL_UNIT_IMAGE_ORDER", order_global_unit_image, 6);
order_ray_order = residue_unit_group_order*2/order_global_unit_image \
  *qfbclassno(32);
assert_equal("ORDER_RAY_GROUP_ORDER", order_ray_order, 12);
assert_equal("MAXIMAL_RAY_14_ORDER", ray14_one.no, order_ray_order);
print("ORDER_TO_MAXIMAL_RAY_14_ISOMORPHISM=1");

automorphism = Mod(-y, y^2 - 2);

\\ At modulus 14, conjugation on A=C6 x C2 x C2 has columns
\\ (4,1,0), (3,0,0), (0,0,1).  Its commutator image is generated by
\\ c=(3,1,0).  Removing infinity_2 has kernel b=(3,0,1).
conjugation14 = matrix(3, 3, row, column, \
  bnrisprincipal(ray14_both, \
    nfgaloisapply(K, automorphism, ray14_both.gen[column]), 0)[row]);
forgetful14 = matrix(2, 3, row, column, \
  bnrisprincipal(ray14_one, ray14_both.gen[column], 0)[row]);
assert_equal("RAY_14_CONJUGATION_MATRIX", conjugation14, \
  [4, 3, 0; 1, 0, 0; 0, 0, 1]);
assert_equal("RAY_14_FORGETFUL_MATRIX", forgetful14, \
  [1, 0, 3; 0, 1, 0]);
commutator14 = vector(3, row, \
  (conjugation14[row, 1] - (row == 1)) % ray14_both.cyc[row]);
kernel14 = [3, 0, 1]~;
assert_equal("RAY_14_COMMUTATOR_GENERATOR", commutator14, [3, 1, 0]);
assert_equal("RAY_14_ONE_PLACE_KERNEL_IMAGE", \
  vector(2, row, sum(column = 1, 3, \
    forgetful14[row, column]*kernel14[column]) % ray14_one.cyc[row]), \
  [0, 0]);
assert_equal("RAY_14_KERNEL_EQUALS_COMMUTATOR", \
  Vec(kernel14) == commutator14, 0);
print("RAY_14_SHINTANI_INDEX=2");

\\ The only nonquadratic proper lowered field is the ray-7 field.
\\ There the commutator generator is (3,1), while the one-place kernel
\\ is (3,0), so the same index-two criterion holds.
conjugation7 = matrix(2, 2, row, column, \
  bnrisprincipal(ray7_both, \
    nfgaloisapply(K, automorphism, ray7_both.gen[column]), 0)[row]);
forgetful7 = matrix(1, 2, row, column, \
  bnrisprincipal(ray7_one, ray7_both.gen[column], 0)[row]);
assert_equal("RAY_7_CONJUGATION_MATRIX", conjugation7, \
  [4, 3; 1, 0]);
assert_equal("RAY_7_FORGETFUL_MATRIX", forgetful7, Mat([2, 3]));
commutator7 = vector(2, row, \
  (conjugation7[row, 1] - (row == 1)) % ray7_both.cyc[row]);
kernel7 = [3, 0]~;
assert_equal("RAY_7_COMMUTATOR_GENERATOR", commutator7, [3, 1]);
assert_equal("RAY_7_ONE_PLACE_KERNEL_IMAGE", \
  vector(1, row, sum(column = 1, 2, \
    forgetful7[row, column]*kernel7[column]) % ray7_one.cyc[row]), \
  [0]);
assert_equal("RAY_7_KERNEL_EQUALS_COMMUTATOR", \
  Vec(kernel7) == commutator7, 0);
print("RAY_7_SHINTANI_INDEX=2");

\\ Conductor lowering from beta=2*phi+1 has two lifts
\\
\\   s_j=((a-b+7j)/14, 2b/14),  j=0,1,
\\
\\ represented by gamma_j=2b*phi-a+b-7j.
moduli = List();
norm_pairs = List();
audit_lift(a, b, j) =
{
  my(gamma_j = 2*b*phi - a + b - 7*j);
  my(divisor_ideal = idealadd(K, idealhnf(K, 14), \
    idealhnf(K, gamma_j)));
  my(lowered_modulus = idealdiv(K, idealhnf(K, 14), divisor_ideal));
  listput(moduli, lowered_modulus);
  listput(norm_pairs, [idealnorm(K, divisor_ideal), \
    idealnorm(K, lowered_modulus)]);
};
for(a = 0, 6, for(b = 0, 6, if(a != 0 || b != 0, \
  for(j = 0, 1, audit_lift(a, b, j)))));

unique_moduli = Set(Vec(moduli));
assert_equal("PRIMITIVE_CHARACTERISTIC_COUNT", (7^2 - 1), 48);
assert_equal("CONDUCTOR_LIFT_COUNT", #moduli, 96);
assert_equal("LOWERED_NORM_PAIRS", Set(Vec(norm_pairs)), \
  [[1, 196], [4, 49], [7, 28], [28, 7]]);
assert_equal("DISTINCT_LOWERED_MODULUS_COUNT", #unique_moduli, 6);

structures = List();
audit_modulus(modulus) =
{
  my(lowered_ray = bnrinit(K, [modulus, [1, 0]], 1));
  listput(structures, [idealnorm(K, modulus), lowered_ray.cyc]);
};
for(index = 1, #unique_moduli, audit_modulus(unique_moduli[index]));
assert_equal("LOWERED_RAY_STRUCTURES", Set(Vec(structures)), \
  [[7, []], [7, [2]], [28, [2]], [49, [6]], [196, [6, 2]]]);

print("ALL_NONQUADRATIC_LOWERED_FIELDS_PASS_SHINTANI_INDEX_TWO=1");
print("DIMENSION_SEVEN_NEXT_UNCONDITIONAL_CANDIDATE=1");

quit();
