"""Seal Cycle 30's exact CRT transport algebra and partial convolution action."""
from __future__ import annotations

from pathlib import Path

from check_cycle_30_crt_synchronization import audit
from cycle_seal_v1 import check_runtime, freeze_inputs, run_cli, sha256

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "discovery/out/cycle30-crt-synchronization"
OUTPUT = ROOT / "artifacts/cycle-30-b030-lrc-crt-synchronization-v1.json"
INPUTS = {
    "preregistration": (ROOT / "docs/cycle-30-b030-lrc-crt-synchronization-preregistration-v1.md", "1b4cb4f1afa9c77123928a440606e9d9f6eb56a829d9f0a42fcaf4a88c8b8054"),
    "h11_source_artifact": (ROOT / "artifacts/cycle-8-b008-lrc-fused-lift-v1.json", "20a20af7bc8a259696e1bcc082e69d3828acea6b7015286d4c289e974eac7de0"),
    "crt_source_artifact": (ROOT / "artifacts/cycle-20-b020-lrc-crt-diagonal-v1.json", "cd2ced396549a819cd891472a1a71a1072dfbd8b322eb096fb2b2ce1841f62c6"),
    "prior_artifact": (ROOT / "artifacts/cycle-29-b029-lrc-ownership-blocker-v2.json", "faf097ebcc22e9e18055cbf4139aef30e17ee85e86ea2096d43b31873f6e8d09"),
    "idea_selection": (ROOT / "discovery/cycle30_crt_synchronization_idea_selection.md", "4e5d1042a5e56feed58c1012ef9c71b6d275cfd1bf82c2ceaf89608e1b8f3805"),
    "primary_engine": (ROOT / "discovery/lrc_crt_synchronization.py", "1c87877ba3fced5840ffee5c17f63bbb65f7f7868f8a014c08db01e16302f331"),
    "independent_replay": (ROOT / "proof/replay_cycle_30_crt_synchronization_independent.py", "edbee5b730afa5b2b0bd62c80646a89109fd6eeb314ea4a43988f3a0d0e2aeed"),
    "convolution_engine": (ROOT / "discovery/lrc_exceptional_convolution.py", "1a6d099326f531f36cf196b28c5cdee8f2cae7d6e313dd03af47ac4464fc38ee"),
    "convolution_independent": (ROOT / "proof/replay_cycle_30_exceptional_convolution_independent.py", "44104be75a3a6437c88f369942b50c0105463a9c274b6571cb8f14bb328c9abe"),
    "audit": (ROOT / "proof/check_cycle_30_crt_synchronization.py", "936563ca8b31c8bbd37298d2252fa5aa0769edb17f6368c088e68923e79c16c5"),
    "soundness": (ROOT / "proof/cycle_30_crt_synchronization_soundness.md", "d494797bac0a4108cc78871cbe2c59af3dddb4ab60b5747955df81037191208d"),
    "test": (ROOT / "tests/test_cycle_30_crt_synchronization.py", "8bebba9da769c0406b9e3373071c5630f668da582671c4a7cd2e2417a804adad"),
    "primary_result": (OUT / "result.json", "eaa9f7185dde55d03453187d8a8e6bccfe9563e022616a1f4be01e8a7feda674"),
    "primary_summary": (OUT / "summary.txt", "290d62aa2075ddf9c526ed48750fe0cd4b9e5a3bec8eef09d7c0eef7c18b5f99"),
    "primary_timing": (ROOT / "discovery/out/cycle30-crt-synchronization.time", "4125a67e846b93373e35bb1c9ea015f9877a39e7d62486ab1a6e68366c83f10d"),
    "independent_result": (OUT / "independent-replay.json", "a7463bdaa3e15b058d0ed0598bf8fb7592c50d917db222d8215d848f63a3c84a"),
    "independent_timing": (OUT / "independent-replay.time", "974629c27148bff2e5b416f64ae64549a81d0cbaa6846ba748f8aa247c7004b0"),
    "convolution_result": (OUT / "convolution-result.json", "e66c19d06389915355ba2283f793acedb7e211283aaa1c2018aa415c359118d2"),
    "convolution_timing": (OUT / "convolution.time", "cf4d3bf51f253a6afd0f67360f43ab0bb0a217e5c3b25407f02013d710a25f75"),
    "convolution_independent_result": (OUT / "convolution-independent.json", "88a33a26522302915701d06c1ed7fb23c3c344fba0d9b617b845e13d616298f2"),
    "convolution_independent_timing": (OUT / "convolution-independent.time", "66d6ee646f260b46a2bdd2b238eeeb9f039b0148a544c2af59a97625fc978d56"),
    "scaffold": (ROOT / "proof/cycle_seal_v1.py", "9494b7693cff5ea537764211fa3a6b980ae96b121fcb35aeb5b13022d550d4e7"),
}


def payload() -> dict[str, object]:
    checked = audit()
    return {
        "artifact_id": "cycle-30-b030-lrc-crt-synchronization-v1",
        "budget_ordinal": "B030",
        "cycle": 30,
        "record_type": "PROVED_TRANSPORT_ALGEBRA_PARTIAL_CONVOLUTION_ACTION",
        "recorded_at_utc": "2026-08-04T14:19:13Z",
        "status": "SEALED",
        "epistemic_status": "PROVED",
        "outcome": "Unit-associated speeds transport bad-time masks exactly within gcd strata. On p199 base 4 / leaf 78, 1,386 transported masks generate a 1,390-atom pointwise algebra, and both exceptional six-point atoms convolve atom-constantly with every mask generator in all 2,772 named profiles.",
        "claim_boundary": "The general transport theorem, complete H11 replay, p199 atom census, and exceptional-atom-by-mask action are proved. Full atom-pair convolution closure is untested; no Schur ring, leaf exclusion, all-survivor closure, or LRC(13) claim is made.",
        "audit": checked,
        "theorems": [
            {"epistemic_status": "PROVED", "statement": "For every unit u modulo q, M_(u*a)=u^(-1)M_a; residues are unit associates exactly within gcd strata."},
            {"epistemic_status": "PROVED", "statement": "The unital pointwise algebra generated by zero-one masks is exactly the function algebra constant on their common membership atoms."},
        ],
        "finite_results": {
            "epistemic_status": "PROVED",
            "h11": {"generated_masks": 20, "atoms": 23, "assignments": 64000, "raw_full_covers": 720, "retained_improper_bases": 0},
            "p199": {"base_index": 4, "leaf_ordinal": 78, "allowed_speeds": 159, "generated_masks": 1386, "atoms": 1390, "atom_sizes": {"1": 2, "2": 1386, "6": 2}, "negation_orbits": 1394, "beyond_negation_reduction": 4},
            "exceptional_action": {"profiles_checked": 2772, "splitting_profiles": 0, "distinct_compressed_profiles": 2079, "independent_replay": "PASS"},
        },
        "cycle_decision": {
            "companion_identity": "/root/darwin_cycle25_short",
            "outcome": "SEALED_FOR_DISTINCT_FULL_CONVOLUTION_QUOTIENT_QUESTION",
            "scope_review": "Mask generators are large unions of atoms; exceptional-atom action on those unions cannot imply arbitrary atom-pair closure because cancellations may hide a split.",
            "strongest_flaw": "The result is a partial module action, not an association scheme or convolution algebra.",
            "independent_ideas": ["test singleton translations, then pair atoms only where exceptional targets can split", "test exceptional-by-pair profiles directly", "defer polynomial calculus until the exact convolution quotient question is answered"],
            "falsifier": "Atoms A,B,C and x,x' in C with unequal representation counts (1_A*1_B)(x) and (1_A*1_B)(x') contain the full convolution-quotient route.",
            "next_action": "Open a distinct cycle asking only whether the 1,390-atom partition is an exact additive convolution quotient, using targeted atom-pair tests before any full table or polynomial campaign.",
        },
        "resources": {"worker_cpus": [0, 1, 2], "reserved_cpu": 3, "aggregate_wall_seconds": 20.2, "largest_peak_rss_kib": 112512, "memory_max_bytes": 4294967296, "temporary_disk_cap_bytes": 5368709120},
        "runtime": check_runtime("Cycle 30 CRT synchronization"),
        "frozen_hashes": freeze_inputs(ROOT, INPUTS),
        "replay": {
            "primary_command": "taskset -c 0-2 .venv/bin/python discovery/lrc_crt_synchronization.py",
            "independent_command": "taskset -c 0-2 .venv/bin/python proof/replay_cycle_30_crt_synchronization_independent.py",
            "convolution_command": "taskset -c 0-2 .venv/bin/python discovery/lrc_exceptional_convolution.py",
            "convolution_independent_command": "taskset -c 0-2 .venv/bin/python proof/replay_cycle_30_exceptional_convolution_independent.py",
            "audit_command": ".venv/bin/python proof/check_cycle_30_crt_synchronization.py",
            "test_command": ".venv/bin/python -m unittest tests.test_cycle_30_crt_synchronization -v",
            "check_command": ".venv/bin/python proof/build_cycle_30_lrc_crt_synchronization.py --check",
        },
        "sealer": {"path": "proof/build_cycle_30_lrc_crt_synchronization.py", "sha256": sha256(Path(__file__))},
    }


if __name__ == "__main__":
    raise SystemExit(run_cli(description=__doc__, output=OUTPUT, payload_factory=payload))
