#!/usr/bin/env python3
"""Direct 80-point Arb cone certificate for RQ-002057.

This uses the original determinant-80 fundamental cones, so no
internal-ray correction or fan convention enters the proof.  A
validated order-12 interval Taylor quadrature makes the large period
151+20*sqrt(57) tractable.  Exact cone coordinates use Fraction and no
PARI L-value enters the analytic certificate.
"""

from __future__ import annotations

import argparse
from fractions import Fraction
from math import gcd

from flint import arb, ctx, fmpz_poly

from certified_taylor_quadrature import certified_taylor
from certify_q7_p7_packet import (
    arb_fraction,
    near_integrand,
    product,
    tail_integrand,
)


SAFE_EXPONENT = 2592
DETERMINANT = 80
CONE_MATRICES = [
    ((1, 51), (1, -29)),
    ((-101, 9), (166, -14)),
    ((-7, 3), (50, -10)),
]
# Multiplication by epsilon=171-40*y on each frozen b-lattice.
# The unit has order three modulo the finite modulus, so the
# ray-congruence unit group is generated by epsilon^3 and a ray-class
# fundamental domain is the union of three adjacent epsilon-cones.
UNIT_ACTION_MATRICES = [
    ((211, -160), (-120, 91)),
    ((5851, 3560), (-9120, -5549)),
    ((571, 80), (-1920, -269)),
]
AFFINE_SHIFTS = [
    (Fraction(1, 9), Fraction(0)),
    (Fraction(1, 9), Fraction(0)),
    (Fraction(19, 9), Fraction(0)),
]


def determinant(first: tuple[int, int], second: tuple[int, int]) -> int:
    return first[0] * second[1] - first[1] * second[0]


def mod_one_upper(value: Fraction) -> Fraction:
    remainder = value - value.numerator // value.denominator
    return Fraction(1) if remainder == 0 else remainder


def matrix_vector(
    matrix: tuple[tuple[int, int], tuple[int, int]],
    vector: tuple[int, int],
) -> tuple[int, int]:
    return (
        matrix[0][0] * vector[0] + matrix[0][1] * vector[1],
        matrix[1][0] * vector[0] + matrix[1][1] * vector[1],
    )


def adjacent_cone_matrix(
    class_log: int,
    unit_step: int,
) -> tuple[tuple[int, int], tuple[int, int]]:
    base = CONE_MATRICES[class_log]
    first = (base[0][0], base[1][0])
    second = (base[0][1], base[1][1])
    action = UNIT_ACTION_MATRICES[class_log]
    for _ in range(unit_step):
        first = matrix_vector(action, first)
        second = matrix_vector(action, second)
    return ((first[0], second[0]), (first[1], second[1]))


def quotient_generator(
    matrix: tuple[tuple[int, int], tuple[int, int]],
    signed_determinant: int,
) -> tuple[int, int]:
    for bound in range(1, 5):
        for first in range(-bound, bound + 1):
            for second in range(-bound, bound + 1):
                if (first, second) == (0, 0):
                    continue
                first_coordinate = Fraction(
                    matrix[1][1] * first - matrix[0][1] * second,
                    signed_determinant,
                )
                second_coordinate = Fraction(
                    -matrix[1][0] * first + matrix[0][0] * second,
                    signed_determinant,
                )
                order = (
                    first_coordinate.denominator
                    * second_coordinate.denominator
                    // gcd(
                        first_coordinate.denominator,
                        second_coordinate.denominator,
                    )
                )
                if order == DETERMINANT:
                    return first, second
    raise RuntimeError("no cyclic quotient generator found")


def cone_points(
    class_log: int,
    unit_step: int,
) -> list[tuple[Fraction, Fraction]]:
    """Enumerate one 80-point adjacent epsilon-cone."""

    matrix = adjacent_cone_matrix(class_log, unit_step)
    first = (matrix[0][0], matrix[1][0])
    second = (matrix[0][1], matrix[1][1])
    signed_determinant = determinant(first, second)
    if abs(signed_determinant) != DETERMINANT:
        raise RuntimeError("fundamental cone determinant changed")
    shift = AFFINE_SHIFTS[class_log]

    generator = quotient_generator(matrix, signed_determinant)

    points = []
    for residue in range(DETERMINANT):
        vector_first = shift[0] + residue * generator[0]
        vector_second = shift[1] + residue * generator[1]
        x_value = Fraction(
            matrix[1][1] * vector_first
            - matrix[0][1] * vector_second,
            signed_determinant,
        )
        y_value = Fraction(
            -matrix[1][0] * vector_first
            + matrix[0][0] * vector_second,
            signed_determinant,
        )
        points.append(
            (mod_one_upper(x_value), mod_one_upper(y_value))
        )
    if len(points) != DETERMINANT or len(set(points)) != DETERMINANT:
        raise RuntimeError("affine cone enumeration is not complete")
    return sorted(points)


def fundamental_log_double_sine(
    argument: arb,
    beta: arb,
    tolerance: Fraction,
) -> tuple[arb, int]:
    """Enclose log S_2(argument | 1,beta), beta=151+20sqrt(57)."""

    linear = beta + 1 - 2 * argument
    if linear.contains(0) and abs(linear).upper() < arb_fraction(tolerance):
        return arb(0), 0

    # With delta=10^-7, |linear|<303, and beta<302,
    # exp(303*delta/2)<100016/100000.  Positive power-series
    # coefficients give the following deliberately rounded rational
    # majorants.
    delta = Fraction(1, 10_000_000)
    exponential_majorant = Fraction(100_016, 100_000)
    numerator_remainder = (
        Fraction(303**4, 1920) * exponential_majorant
    )
    denominator_remainder = (
        Fraction(302**4, 1920) * exponential_majorant
        + Fraction(1, 1920) * exponential_majorant
        + (
            Fraction(302**2, 24)
            * Fraction(1, 24)
            * exponential_majorant**2
        )
    )
    denominator_increment = (
        Fraction(302**2 + 1, 24) * exponential_majorant
        + (
            Fraction(302**2, 24)
            * Fraction(1, 24)
            * exponential_majorant**2
            * delta**2
        )
    )
    coefficient_majorant = Fraction(303**2 + 302**2 + 1, 24)
    second_order_majorant = Fraction(80_000_000)
    if not (
        Fraction(1, 1 - Fraction(303, 20_000_000))
        < exponential_majorant
        and numerator_remainder < 4_400_000
        and denominator_remainder < 4_350_000
        and denominator_increment < 3_801
        and 2
        * (
            Fraction(4_400_000)
            + Fraction(4_350_000)
            + coefficient_majorant * Fraction(3_801)
        )
        < second_order_majorant
    ):
        raise RuntimeError("large-period Taylor majorant check failed")
    if not (
        abs(linear) < 303
        and beta > 301
        and beta < 302
        and argument > arb(2) / 5
        and beta + 1 - argument > arb(2) / 5
    ):
        raise RuntimeError("large-period analytic hypotheses failed")

    zero_value = (
        linear * (linear**2 - beta**2 - 1) / (24 * beta)
    )
    zero_remainder = second_order_majorant * delta**3 / 3
    near_value = zero_value * arb_fraction(delta)
    near_value += arb(0, arb_fraction(zero_remainder).upper())

    near_function = near_integrand(argument, beta)
    segment_left = delta
    near_panels = 0
    while segment_left < 1:
        segment_right = min(Fraction(1), 4 * segment_left)
        segment = certified_taylor(
            near_function,
            segment_left,
            segment_right,
            tolerance * (segment_right - segment_left) / 8,
        )
        near_value += segment.value
        near_panels += segment.panels
        segment_left = segment_right

    cutoff = Fraction(30)
    tail = certified_taylor(
        tail_integrand(argument, beta),
        Fraction(0),
        cutoff,
        tolerance / 4,
    )
    # For v>=30 and z>0, v/z+1>1.  The first five positive
    # terms of exp(1) exceed 8/3, so exp(-1)<3/8.  Both
    # exponential denominator factors have magnitude >5/8;
    # their product exceeds 25/64 and v+z>30.  The difference
    # of the two terms is <1/4, giving the tail below.
    exp_one_partial = sum(
        Fraction(1, product(range(1, index + 1)))
        for index in range(5)
    )
    if not exp_one_partial > Fraction(8, 3):
        raise RuntimeError("tail exponential majorant check failed")
    tail_remainder = (-arb_fraction(cutoff)).exp() / 4
    tail_value = tail.value + arb(0, tail_remainder.upper())
    boundary = -linear / beta
    return near_value + boundary + tail_value, near_panels + tail.panels


def class_log_value(
    points: list[tuple[Fraction, Fraction]],
    beta: arb,
    tolerance: Fraction,
) -> tuple[arb, int]:
    result = arb(0)
    panels = 0
    for x_value, y_value in points:
        argument = arb_fraction(x_value) + arb_fraction(y_value) * beta
        value, used = fundamental_log_double_sine(
            argument, beta, tolerance / len(points)
        )
        result += value
        panels += used
    return 2 * result, panels


def voutier_lower_bound() -> arb:
    bounds = []
    for degree in range(3, 25):
        degree_ball = arb(degree)
        bounds.append(
            (degree_ball.log().log() / degree_ball.log()) ** 3
            / (4 * degree)
        )
    return arb(min(bound.lower() for bound in bounds))


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--digits", type=int, default=90)
    parser.add_argument("--tolerance", default="1e-10")
    arguments = parser.parse_args()
    tolerance = Fraction(arguments.tolerance)
    if tolerance <= 0:
        raise ValueError("tolerance must be positive")
    ctx.dps = arguments.digits
    ctx.cap = 16
    beta = 151 + 20 * arb(57).sqrt()
    point_sets = [
        [
            cone_points(class_log, unit_step)
            for unit_step in range(3)
        ]
        for class_log in range(3)
    ]

    polynomial = fmpz_poly([
        1, -69, 1377, -6694, 7590, -15594, 10791,
        -15594, 7590, -6694, 1377, -69, 1,
    ])
    real_roots = [
        root.real
        for root, multiplicity in polynomial.complex_roots()
        if multiplicity == 1 and root.imag.contains(0)
    ]
    if len(real_roots) != 6:
        raise RuntimeError("candidate polynomial real-root count changed")
    windows = [
        (Fraction(5709, 1000), Fraction(5710, 1000)),
        (Fraction(28, 1000), Fraction(29, 1000)),
        (Fraction(35, 1000), Fraction(36, 1000)),
        (Fraction(175, 1000), Fraction(176, 1000)),
        (Fraction(34732, 1000), Fraction(34733, 1000)),
        (Fraction(27792, 1000), Fraction(27793, 1000)),
    ]
    candidates = []
    for left, right in windows:
        selected = [
            root
            for root in real_roots
            if root > arb_fraction(left) and root < arb_fraction(right)
        ]
        if len(selected) != 1:
            raise RuntimeError(
                f"isolating window [{left},{right}] selected {len(selected)}"
            )
        candidates.append(selected[0])

    analytic_logs = []
    total_panels = 0
    for class_log in range(3):
        value = arb(0)
        panels = 0
        for unit_step in range(3):
            cone_value, cone_panels = class_log_value(
                point_sets[class_log][unit_step],
                beta,
                tolerance / 3,
            )
            value += cone_value
            panels += cone_panels
        analytic_logs.append(value)
        total_panels += panels
        print(f"CLASS_{class_log}_ADJACENT_CONES=3")
        print(f"CLASS_{class_log}_CONE_POINTS=240")
    analytic_logs.extend([-value for value in analytic_logs[:3]])

    maximum_difference = arb(0)
    for class_log, (analytic, candidate) in enumerate(
        zip(analytic_logs, candidates, strict=True)
    ):
        algebraic = candidate.log()
        difference = analytic - algebraic
        if not difference.contains(0):
            raise RuntimeError(
                f"class {class_log}: analytic and algebraic balls disjoint: "
                f"{difference}"
            )
        maximum_difference = max(
            maximum_difference, arb(abs(difference).upper())
        )
        print(f"CLASS_{class_log}_ANALYTIC_LOG={analytic}")
        print(f"CLASS_{class_log}_ALGEBRAIC_ROOT={candidate}")
        print(f"CLASS_{class_log}_LOG_DIFFERENCE={difference}")

    powered_height_upper = SAFE_EXPONENT * maximum_difference
    voutier_lower = voutier_lower_bound()
    margin = voutier_lower / powered_height_upper
    quadratic_fallback = ((1 + arb(5).sqrt()) / 2).log() / 2
    if not (
        margin > 100
        and quadratic_fallback > powered_height_upper
    ):
        raise RuntimeError("height-rigidity margin did not clear")

    print("FUNDAMENTAL_CONE_DETERMINANT=80")
    print("FUNDAMENTAL_UNIT_MOD_FINITE_ORDER=3")
    print("RAY_CONGRUENCE_UNIT_GENERATOR=EPSILON^3")
    print("ADJACENT_EPSILON_CONES_PER_CLASS=3")
    print("CONE_POINT_COUNT_PER_CLASS=240")
    print("INTERNAL_FAN_CORRECTIONS_USED=0")
    print("QUADRATURE_ORDER=12")
    print(f"TOTAL_TAYLOR_PANELS={total_panels}")
    print(f"SHINTANI_SAFE_EXPONENT={SAFE_EXPONENT}")
    print(f"POWERED_HEIGHT_UPPER={powered_height_upper}")
    print(f"VOUTIER_DEGREE_3_TO_24_LOWER={voutier_lower}")
    print(f"VOUTIER_MARGIN={margin}")
    print(f"QUADRATIC_HEIGHT_FALLBACK={quadratic_fallback}")
    print("DEGREE_1_FALLBACK=POSITIVE_RATIONAL_UNIT_IS_1")
    print("RQ57_NORM27_ANALYTIC_ARB_CERTIFIED=1")
    print("RQ57_NORM27_PACKET_IDENTITY_VERIFIED=1")


if __name__ == "__main__":
    main()
