#!/usr/bin/env python3
"""Certify the explicit Q(sqrt(7)), p_7 infinity_2 Stark packet.

The arithmetic input is Yamamoto's two-dimensional Shintani factorization
with the cone generated by lambda and lambda*epsilon, where

    epsilon = 8 + 3*sqrt(7),
    lambda  = (7 - 2*sqrt(7)) / 3^r.

For the ray class represented by (3)^r, the half-open parallelotope meets
1 + p_7/(3)^r in nine points.  Homogeneity removes lambda, leaving nine
double sines with periods (1, epsilon).  Forgetting the other real place
and differencing by the totally negative sign class gives twice the
logarithm of this single-place factor.

All lattice calculations below use Fraction.  All transcendental
calculations use Arb balls and an adaptive Simpson rule with an interval
fourth-derivative bound.  No PARI L-value enters the certificate.
"""

from __future__ import annotations

import argparse
from dataclasses import dataclass
from fractions import Fraction

from flint import arb, arb_series, ctx, fmpz_poly


SAFE_EXPONENT = 4032
MATRIX = ((1, 2), (-2, 5))
DETERMINANT = 9


def arb_fraction(value: Fraction) -> arb:
    return arb(value.numerator) / value.denominator


def interval(left: Fraction, right: Fraction) -> arb:
    left_ball = arb_fraction(left)
    right_ball = arb_fraction(right)
    midpoint = (left_ball + right_ball) / 2
    return midpoint + arb(0, ((right_ball - left_ball) / 2).upper())


def sinh(value):
    if isinstance(value, arb_series):
        return (value.exp() - (-value).exp()) / 2
    return value.sinh()


def exponential(value):
    return value.exp()


@dataclass
class CertifiedIntegral:
    value: arb
    panels: int


def simpson_panel(function, left: Fraction, right: Fraction) -> arb:
    middle = (left + right) / 2
    width = arb_fraction(right - left)
    return width * (
        function(arb_fraction(left))
        + 4 * function(arb_fraction(middle))
        + function(arb_fraction(right))
    ) / 6


def fourth_derivative_bound(
    function, left: Fraction, right: Fraction
) -> arb:
    variable = arb_series([interval(left, right), arb(1)])
    coefficient = function(variable)[4]
    return 24 * abs(coefficient)


def certified_simpson(
    function,
    left: Fraction,
    right: Fraction,
    tolerance: Fraction,
    *,
    max_depth: int = 30,
) -> CertifiedIntegral:
    accepted = arb(0)
    panels = 0
    stack = [(left, right, 0)]
    total_width = right - left
    while stack:
        panel_left, panel_right, depth = stack.pop()
        width = panel_right - panel_left
        try:
            derivative_bound = fourth_derivative_bound(
                function, panel_left, panel_right
            )
            error = derivative_bound * arb_fraction(width) ** 5 / 2880
            allowed = tolerance * width / total_width
        except (ValueError, ZeroDivisionError):
            error = arb("nan")
            allowed = Fraction(0)
        if error.is_finite() and error.upper() <= arb_fraction(allowed):
            accepted += simpson_panel(function, panel_left, panel_right)
            accepted += arb(0, error.upper())
            panels += 1
            continue
        if depth >= max_depth:
            raise RuntimeError(
                f"integration failed on [{panel_left}, {panel_right}]: "
                f"error {error}"
            )
        middle = (panel_left + panel_right) / 2
        stack.append((middle, panel_right, depth + 1))
        stack.append((panel_left, middle, depth + 1))
    return CertifiedIntegral(accepted, panels)


def near_integrand(argument: arb, beta: arb):
    linear = beta + 1 - 2 * argument

    def integrand(value):
        return (
            sinh(linear * value / 2)
            / (
                2
                * value
                * sinh(beta * value / 2)
                * sinh(value / 2)
            )
            - linear / (beta * value**2)
        )

    return integrand


def tail_integrand(argument: arb, beta: arb):
    complement = beta + 1 - argument

    def term(z_value, value):
        return exponential(-z_value) / (
            (exponential(-beta * (value / z_value + 1)) - 1)
            * (exponential(-(value / z_value + 1)) - 1)
            * (value + z_value)
        )

    def integrand(value):
        return exponential(-value) * (
            term(argument, value) - term(complement, value)
        )

    return integrand


def fundamental_log_double_sine(
    argument: arb,
    beta: arb,
    tolerance: Fraction,
) -> tuple[arb, int]:
    """Enclose log S_2(argument | 1,beta) for 0 < argument < 1+beta."""

    linear = beta + 1 - 2 * argument
    if linear.contains(0) and abs(linear).upper() < arb_fraction(tolerance):
        return arb(0), 0

    # Put H_c(t)=sinh(ct/2)/(ct/2).  For |c|<17 and
    # 0 <= t <= delta=10^-6, positivity of its power series and
    # exp(17*delta/2) < 100001/100000 give the following rational
    # remainder bounds.  The same quotient expansion as in the
    # Papers-I/II Arb certificates then bounds the error after the
    # constant term by 660*t^2.
    delta = Fraction(1, 1_000_000)
    exponential_majorant = Fraction(100_001, 100_000)
    numerator_remainder = (
        Fraction(17**4, 1920) * exponential_majorant
    )
    denominator_remainder = (
        Fraction(16**4, 1920) * exponential_majorant
        + Fraction(1, 1920) * exponential_majorant
        + (
            Fraction(16**2, 24)
            * Fraction(1, 24)
            * exponential_majorant**2
        )
    )
    denominator_increment = (
        Fraction(16**2 + 1, 24) * exponential_majorant
        + (
            Fraction(16**2, 24)
            * Fraction(1, 24)
            * exponential_majorant**2
            * delta**2
        )
    )
    coefficient_majorant = Fraction(17**2 + 16**2 + 1, 24)
    second_order_majorant = Fraction(660)
    if not (
        Fraction(1, 1 - Fraction(17, 2_000_000))
        < exponential_majorant
        and numerator_remainder < 44
        and denominator_remainder < 35
        and denominator_increment < 11
        and 2
        * (
            Fraction(44)
            + Fraction(35)
            + coefficient_majorant * Fraction(11)
        )
        < second_order_majorant
    ):
        raise RuntimeError("large-period Taylor majorant check failed")
    if not (
        abs(linear) < 17
        and beta > 15
        and beta < 16
        and argument > arb(1) / 2
        and beta + 1 - argument > arb(1) / 2
    ):
        raise RuntimeError("large-period analytic hypotheses failed")

    zero_value = (
        linear * (linear**2 - beta**2 - 1) / (24 * beta)
    )
    zero_remainder = second_order_majorant * delta**3 / 3
    near_value = zero_value * arb_fraction(delta)
    near_value += arb(0, arb_fraction(zero_remainder).upper())

    near_function = near_integrand(argument, beta)
    segment_left = delta
    near_panels = 0
    while segment_left < 1:
        segment_right = min(Fraction(1), 4 * segment_left)
        segment = certified_simpson(
            near_function,
            segment_left,
            segment_right,
            tolerance * (segment_right - segment_left) / 8,
        )
        near_value += segment.value
        near_panels += segment.panels
        segment_left = segment_right

    cutoff = Fraction(36)
    tail = certified_simpson(
        tail_integrand(argument, beta),
        Fraction(0),
        cutoff,
        tolerance / 4,
    )
    # At v>=36 and 1/2<z<17, v/z+1>53/17>3.
    # The first nine positive terms of exp(3) exceed 20, so each
    # exponential denominator has absolute value >19/20.  Their
    # product is >9/10 and v+z>36; each term is <1/32.  The
    # difference therefore contributes less than exp(-36)/16.
    exp_three_partial = sum(
        Fraction(3**index, 1)
        / product(range(1, index + 1))
        for index in range(9)
    )
    if not exp_three_partial > 20:
        raise RuntimeError("tail exponential majorant check failed")
    tail_remainder = (-arb_fraction(cutoff)).exp() / 16
    tail_value = tail.value + arb(0, tail_remainder.upper())
    boundary = -linear / beta
    return near_value + boundary + tail_value, near_panels + tail.panels


def product(values) -> int:
    result = 1
    for value in values:
        result *= value
    return result


def cone_points(class_log: int) -> list[tuple[Fraction, Fraction]]:
    """Enumerate P(lambda,lambda*epsilon) intersect (1+b) exactly."""

    shift = Fraction(3**class_log, 7)
    points: list[tuple[Fraction, Fraction]] = []
    # In b-coordinates the cone lattice has matrix [[1,2],[-2,5]]
    # and the affine coset has shift (3^r/7,0).  The displayed bound
    # is much larger than the four-vertex bound for r<=5.
    for first in range(-100, 101):
        for second in range(-100, 101):
            vector_first = shift + first
            vector_second = Fraction(second)
            x_value = (
                5 * vector_first - 2 * vector_second
            ) / DETERMINANT
            y_value = (
                2 * vector_first + vector_second
            ) / DETERMINANT
            if 0 < x_value <= 1 and 0 < y_value <= 1:
                points.append((x_value, y_value))
    if len(points) != DETERMINANT:
        raise RuntimeError(
            f"class {class_log}: expected 9 cone points, got {len(points)}"
        )
    return sorted(points)


def verify_complement_symmetry(
    points: list[list[tuple[Fraction, Fraction]]],
) -> None:
    for class_log in range(3):
        complements = sorted(
            (1 - x_value, 1 - y_value)
            for x_value, y_value in points[class_log]
        )
        # None of these points is on the excluded zero boundary.
        if complements != points[class_log + 3]:
            raise RuntimeError(
                f"cone complement symmetry failed for class {class_log}"
            )


def class_log_value(
    points: list[tuple[Fraction, Fraction]],
    beta: arb,
    tolerance: Fraction,
) -> tuple[arb, int]:
    result = arb(0)
    panels = 0
    for x_value, y_value in points:
        argument = arb_fraction(x_value) + arb_fraction(y_value) * beta
        value, used = fundamental_log_double_sine(
            argument, beta, tolerance / len(points)
        )
        result += value
        panels += used
    # The one-place differenced invariant is twice the surviving
    # real-place factor.
    return 2 * result, panels


def voutier_lower_bound() -> arb:
    bounds = []
    for degree in range(3, 25):
        degree_ball = arb(degree)
        bounds.append(
            (degree_ball.log().log() / degree_ball.log()) ** 3
            / (4 * degree)
        )
    lower = min(bound.lower() for bound in bounds)
    return arb(lower)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--digits", type=int, default=80)
    parser.add_argument("--tolerance", default="1e-11")
    arguments = parser.parse_args()
    tolerance = Fraction(arguments.tolerance)
    if tolerance <= 0:
        raise ValueError("tolerance must be positive")

    ctx.dps = arguments.digits
    ctx.cap = 6
    beta = 8 + 3 * arb(7).sqrt()
    point_sets = [cone_points(class_log) for class_log in range(6)]
    verify_complement_symmetry(point_sets)

    polynomial = fmpz_poly([
        1, -12, 52, -108, 124, -92, 63,
        -92, 124, -108, 52, -12, 1,
    ])
    real_roots = [
        root.real
        for root, multiplicity in polynomial.complex_roots()
        if multiplicity == 1 and root.imag.contains(0)
    ]
    if len(real_roots) != 6:
        raise RuntimeError("candidate polynomial real-root count changed")
    windows = [
        (Fraction(5325, 1000), Fraction(5326, 1000)),
        (Fraction(2713, 1000), Fraction(2714, 1000)),
        (Fraction(2251, 1000), Fraction(2252, 1000)),
        (Fraction(187, 1000), Fraction(188, 1000)),
        (Fraction(368, 1000), Fraction(369, 1000)),
        (Fraction(444, 1000), Fraction(445, 1000)),
    ]
    candidates = []
    for left, right in windows:
        selected = [
            root
            for root in real_roots
            if root > arb_fraction(left) and root < arb_fraction(right)
        ]
        if len(selected) != 1:
            raise RuntimeError(
                f"isolating window [{left},{right}] selected {len(selected)}"
            )
        candidates.append(selected[0])

    analytic_logs: list[arb] = []
    total_panels = 0
    for class_log in range(3):
        value, panels = class_log_value(
            point_sets[class_log], beta, tolerance
        )
        analytic_logs.append(value)
        total_panels += panels
    analytic_logs.extend([-value for value in analytic_logs[:3]])

    maximum_difference = arb(0)
    for class_log, (analytic, candidate) in enumerate(
        zip(analytic_logs, candidates, strict=True)
    ):
        algebraic = candidate.log()
        difference = analytic - algebraic
        if not difference.contains(0):
            raise RuntimeError(
                f"class {class_log}: analytic and algebraic balls disjoint: "
                f"{difference}"
            )
        maximum_difference = max(
            maximum_difference, arb(abs(difference).upper())
        )
        print(f"CLASS_{class_log}_CONE_POINTS={len(point_sets[class_log])}")
        print(f"CLASS_{class_log}_ANALYTIC_LOG={analytic}")
        print(f"CLASS_{class_log}_ALGEBRAIC_ROOT={candidate}")
        print(f"CLASS_{class_log}_LOG_DIFFERENCE={difference}")

    powered_height_upper = SAFE_EXPONENT * maximum_difference
    voutier_lower = voutier_lower_bound()
    margin = voutier_lower / powered_height_upper
    quadratic_fallback = arb(5).sqrt()
    quadratic_fallback = ((1 + quadratic_fallback) / 2).log() / 2
    if not (
        margin > 100
        and quadratic_fallback > powered_height_upper
    ):
        raise RuntimeError("height-rigidity margin did not clear")

    print(f"CONE_LATTICE_DETERMINANT={DETERMINANT}")
    print("CONE_POINT_COUNT_PER_CLASS=9")
    print("CONE_COMPLEMENT_SYMMETRY=VERIFIED")
    print(f"TOTAL_SIMPSON_PANELS={total_panels}")
    print(f"SHINTANI_SAFE_EXPONENT={SAFE_EXPONENT}")
    print(f"POWERED_HEIGHT_UPPER={powered_height_upper}")
    print(f"VOUTIER_DEGREE_3_TO_24_LOWER={voutier_lower}")
    print(f"VOUTIER_MARGIN={margin}")
    print(f"QUADRATIC_HEIGHT_FALLBACK={quadratic_fallback}")
    print("DEGREE_1_FALLBACK=POSITIVE_RATIONAL_UNIT_IS_1")
    print("Q7_P7_ANALYTIC_ARB_CERTIFIED=1")
    print("Q7_P7_PACKET_IDENTITY_VERIFIED=1")


if __name__ == "__main__":
    main()
