// Exact bounded S3 KKT/exchange reconnaissance for C62.
#include <algorithm>
#include <array>
#include <cstdint>
#include <filesystem>
#include <fstream>
#include <map>
#include <string>
#include <vector>
using I=__int128_t;
static constexpr std::array<std::array<int,3>,5>N{{{{2,3,4}},{{0,3,4}},{{0,1,4}},{{0,1,2}},{{1,2,3}}}};
struct G{std::vector<std::array<int,3>>p;int m[6][6],iv[6],cl[6];};
static G group(){G g;std::array<int,3>a{0,1,2};do g.p.push_back(a);while(std::next_permutation(a.begin(),a.end()));std::map<std::array<int,3>,int>x;for(int i=0;i<6;++i)x[g.p[i]]=i;for(int i=0;i<6;++i)for(int j=0;j<6;++j){std::array<int,3>z;for(int k=0;k<3;++k)z[k]=g.p[i][g.p[j][k]];g.m[i][j]=x[z];}for(int i=0;i<6;++i)for(int j=0;j<6;++j)if(g.m[i][j]==0&&g.m[j][i]==0)g.iv[i]=j;for(int z=0;z<6;++z){int v=z,n=1;while(v){v=g.m[v][z];++n;}g.cl[z]=n==1?0:n==2?1:2;}return g;}
static I num(const G&g,const std::array<long long,6>&a,std::array<I,6>*gradient=nullptr){I out=0;if(gradient)gradient->fill(0);for(int x1=0;x1<6;++x1)for(int x2=0;x2<6;++x2)for(int x3=0;x3<6;++x3)for(int x4=0;x4<6;++x4){int x[5]{0,x1,x2,x3,x4};I sums[5]{},ds[5][6]{};for(int j=0;j<5;++j)for(int y=0;y<6;++y){I z=1;int hits[3];for(int k=0;k<3;++k){int h=g.m[g.iv[x[N[j][k]]]][y];hits[k]=h;z*=a[h];}sums[j]+=z;for(int k=0;k<3;++k){I partial=1;for(int r=0;r<3;++r)if(r!=k)partial*=a[hits[r]];ds[j][hits[k]]+=partial;}}I product=1;for(I s:sums)product*=s;out+=product;if(gradient)for(int j=0;j<5;++j){I other=1;for(int k=0;k<5;++k)if(k!=j)other*=sums[k];for(int h=0;h<6;++h)(*gradient)[h]+=ds[j][h]*other;}}
return out;}
static std::string text(I x){if(!x)return"0";bool neg=x<0;if(neg)x=-x;std::string s;while(x){s.push_back(char('0'+x%10));x/=10;}if(neg)s.push_back('-');std::reverse(s.begin(),s.end());return s;}
static I pow6(){I z=1;for(int k=0;k<15;++k)z*=6;return z;}
struct Row{I f;std::array<long long,6>a;};
int main(int ac,char**av){if(ac!=3)return 2;int height=std::stoi(av[1]);std::filesystem::create_directories(av[2]);G g=group();I scale=pow6();std::array<Row,64>best{};std::array<bool,64>seen{};long long rows=0,negative=0,zero=0,exchange_fail=0,kkt_rows=0;I global_min=0;bool have_global=false;std::array<long long,6>global_a{};std::ofstream failures(std::string(av[2])+"/exchange-failures.tsv"),kktout(std::string(av[2])+"/grid-kkt.tsv");failures<<"a\tdeficit\tclass\thigh\tlow\tderivative\n";kktout<<"a\tmask\tdeficit\tcentral\n";
for(int a0=0;a0<=height;++a0)for(int a1=0;a1<=height-a0;++a1)for(int a2=0;a2<=height-a0-a1;++a2)for(int a3=0;a3<=height-a0-a1-a2;++a3)for(int a4=0;a4<=height-a0-a1-a2-a3;++a4){std::array<long long,6>a{a0,a1,a2,a3,a4,height-a0-a1-a2-a3-a4};std::array<long long,6>b{};long long st=a[1]+a[2]+a[5],sc=a[3]+a[4];b[0]=6*a[0];for(int h:{1,2,5})b[h]=2*st;for(int h:{3,4})b[h]=3*sc;std::array<I,6>da,db;I f=scale*num(g,a,&da)-num(g,b,&db);std::array<I,6>grad{};for(int h=0;h<6;++h){if(g.cl[h]==0)grad[h]=scale*da[h]-6*db[0];else if(g.cl[h]==1)grad[h]=scale*da[h]-2*(db[1]+db[2]+db[5]);else grad[h]=scale*da[h]-3*(db[3]+db[4]);}int mask=0;for(int h=0;h<6;++h)if(a[h])mask|=1<<h;if(!seen[mask]||f<best[mask].f){seen[mask]=true;best[mask]={f,a};}++rows;if(f<0)++negative;if(f==0)++zero;if(!have_global||f<global_min){have_global=true;global_min=f;global_a=a;}int first=-1;bool kkt=true;for(int h=0;h<6;++h)if(a[h]){if(first<0)first=h;else if(grad[h]!=grad[first])kkt=false;}if(first>=0)for(int h=0;h<6;++h)if(!a[h]&&grad[h]<grad[first])kkt=false;if(kkt){++kkt_rows;for(int h=0;h<6;++h){if(h)kktout<<',';kktout<<a[h];}bool central=a[1]==a[2]&&a[2]==a[5]&&a[3]==a[4];kktout<<'\t'<<mask<<'\t'<<text(f)<<'\t'<<(central?1:0)<<'\n';}for(int cl=1;cl<=2;++cl)for(int i=0;i<6;++i)for(int j=0;j<6;++j)if(g.cl[i]==cl&&g.cl[j]==cl&&a[i]>a[j]){I deriv=grad[j]-grad[i];if(deriv>=0){++exchange_fail;if(exchange_fail<=10000){for(int h=0;h<6;++h){if(h)failures<<',';failures<<a[h];}failures<<'\t'<<text(f)<<'\t'<<cl<<'\t'<<i<<'\t'<<j<<'\t'<<text(deriv)<<'\n';}}}}
std::ofstream o(std::string(av[2])+"/summary.json");o<<"{\n\"status\":\"PASS\",\n\"height\":"<<height<<",\n\"rows\":"<<rows<<",\n\"negative_rows\":"<<negative<<",\n\"zero_rows\":"<<zero<<",\n\"grid_kkt_rows\":"<<kkt_rows<<",\n\"nonnegative_equalizing_exchange_rows\":"<<exchange_fail<<",\n\"global_min_deficit\":\""<<text(global_min)<<"\",\n\"global_min_a\":[";for(int h=0;h<6;++h){if(h)o<<',';o<<global_a[h];}o<<"],\n\"face_minima\":[";bool first=true;for(int m=0;m<64;++m)if(seen[m]){if(!first)o<<',';first=false;o<<"{\"mask\":"<<m<<",\"deficit\":\""<<text(best[m].f)<<"\",\"a\":[";for(int h=0;h<6;++h){if(h)o<<',';o<<best[m].a[h];}o<<"]}";}o<<"]\n}\n";}
